apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 850497296173.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 850497296173.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 79ae0cc5
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
